import type { LifeTile } from '../../model/types'

/** Small life-achievement stories drawn whenever a player gains life tiles. */
export const LIFE_TILE_DECK: readonly LifeTile[] = [
  { id: 'tile-ran-a-marathon', title: 'Ran a Marathon', value: 15_000, icon: 'tile:marathon' },
  { id: 'tile-wrote-a-novel', title: 'Wrote a Novel', value: 40_000, icon: 'tile:novel' },
  { id: 'tile-adopted-a-rescue-dog', title: 'Adopted a Rescue Dog', value: 12_000, icon: 'tile:rescue-dog' },
  { id: 'tile-learned-to-surf', title: 'Learned to Surf', value: 14_000, icon: 'tile:surfing' },
  { id: 'tile-started-a-vegetable-garden', title: 'Started a Vegetable Garden', value: 10_000, icon: 'tile:vegetable-garden' },
  { id: 'tile-won-a-cooking-contest', title: 'Won a Cooking Contest', value: 18_000, icon: 'tile:cooking-contest' },
  { id: 'tile-backpacked-three-countries', title: 'Backpacked Three Countries', value: 25_000, icon: 'tile:backpacking' },
  { id: 'tile-released-an-indie-album', title: 'Released an Indie Album', value: 35_000, icon: 'tile:indie-album' },
  { id: 'tile-built-a-backyard-treehouse', title: 'Built a Backyard Treehouse', value: 16_000, icon: 'tile:treehouse' },
  { id: 'tile-ran-a-viral-food-blog', title: 'Ran a Viral Food Blog', value: 45_000, icon: 'tile:food-blog' },
  { id: 'tile-finished-a-triathlon', title: 'Finished a Triathlon', value: 22_000, icon: 'tile:triathlon' },
  { id: 'tile-volunteered-at-a-shelter', title: 'Volunteered at a Shelter', value: 11_000, icon: 'tile:animal-shelter' },
  { id: 'tile-opened-a-lemonade-empire', title: 'Opened a Lemonade Empire', value: 20_000, icon: 'tile:lemonade-stand' },
  { id: 'tile-painted-a-downtown-mural', title: 'Painted a Downtown Mural', value: 30_000, icon: 'tile:mural' },
  { id: 'tile-earned-a-pilots-license', title: "Earned a Pilot's License", value: 60_000, icon: 'tile:mural' },
  { id: 'tile-launched-a-hit-podcast', title: 'Launched a Hit Podcast', value: 50_000, icon: 'tile:podcast' },
  { id: 'tile-patented-a-clever-gadget', title: 'Patented a Clever Gadget', value: 90_000, icon: 'tile:invention' },
  { id: 'tile-won-the-fantasy-league', title: 'Won the Fantasy League', value: 10_000, icon: 'tile:fantasy-league' },
  { id: 'tile-rescued-a-stray-kitten', title: 'Rescued a Stray Kitten', value: 12_000, icon: 'tile:rescue-kitten' },
  { id: 'tile-climbed-a-famous-peak', title: 'Climbed a Famous Peak', value: 55_000, icon: 'tile:mountain-climb' },
  { id: 'tile-sold-pottery-worldwide', title: 'Sold Pottery Worldwide', value: 18_000, icon: 'tile:pottery' },
  { id: 'tile-coached-a-youth-team', title: 'Coached a Youth Team', value: 15_000, icon: 'tile:youth-coach' },
  { id: 'tile-wrote-a-hit-jingle', title: 'Wrote a Hit Jingle', value: 70_000, icon: 'tile:jingle' },
  { id: 'tile-grew-a-prize-pumpkin', title: 'Grew a Prize Pumpkin', value: 13_000, icon: 'tile:prize-pumpkin' },
  { id: 'tile-backed-a-friends-startup', title: "Backed a Friend's Startup", value: 150_000, icon: 'tile:prize-pumpkin' },
  { id: 'tile-restored-a-vintage-motorcycle', title: 'Restored a Vintage Motorcycle', value: 42_000, icon: 'tile:vintage-motorcycle' },
  { id: 'tile-threw-the-best-block-party', title: 'Threw the Best Block Party', value: 12_000, icon: 'space:neighborhood-bbq' },
  { id: 'tile-won-the-chili-cook-off', title: 'Won the Chili Cook-Off', value: 16_000, icon: 'tile:cooking-contest' },
  { id: 'tile-sailed-the-whole-coast', title: 'Sailed the Whole Coast', value: 32_000, icon: 'space:sunset-ahead' },
  { id: 'tile-designed-a-city-park', title: 'Designed a City Park', value: 48_000, icon: 'tile:vegetable-garden' },
  { id: 'tile-fostered-a-whole-litter', title: 'Fostered a Whole Litter', value: 14_000, icon: 'tile:rescue-kitten' },
  { id: 'tile-baked-for-the-whole-town', title: 'Baked for the Whole Town', value: 11_000, icon: 'space:garage-sale' },
  { id: 'tile-taught-a-sold-out-class', title: 'Taught a Sold-Out Class', value: 24_000, icon: 'space:conference-talk' },
  { id: 'tile-hiked-the-long-trail', title: 'Hiked the Long Trail', value: 28_000, icon: 'tile:backpacking' },
  { id: 'tile-restored-an-old-theatre', title: 'Restored an Old Theatre', value: 65_000, icon: 'tile:mural' },
  { id: 'tile-named-a-new-beetle', title: 'Named a New Beetle', value: 80_000, icon: 'tile:invention' },
]
