import type { IconName } from '@domain/model/icons'

import type { GlyphCategory } from './art/glyphs'

/**
 * Collapses every subject the domain can name onto the sixteen category
 * glyphs. This is what the board (and any other small rendering) shows: the
 * glyph says what *kind* of thing a space is — money in, money out, a hazard,
 * a milestone — and the tile's printed label says which one.
 *
 * Two rules kept the mapping honest:
 *
 *   • Ordinary spaces map by their **mechanical effect**, not their flavour —
 *     "Tuition Bill" is an expense arrow, "Poker Night" is a clover — so a
 *     glance at the board reads as gameplay.
 *   • The milestone glyphs (mortarboard, heart, pram, house, sunset) are
 *     **reserved for their beats**. Nursery Setup is an expense, not a pram,
 *     so New Baby stays unmistakable.
 *
 * The `Record<IconName, …>` annotation makes a missing mapping a compile
 * error, exactly like the art registry.
 */
export const categoryOf: Record<IconName, GlyphCategory> = {
  'career:architect': 'career',
  'career:construction-foreman': 'career',
  'career:corporate-lawyer': 'career',
  'career:delivery-courier': 'career',
  'career:food-truck-owner': 'career',
  'career:game-designer': 'career',
  'career:marine-biologist': 'career',
  'career:pastry-chef': 'career',
  'career:pet-groomer': 'career',
  'career:salon-owner': 'career',
  'career:software-engineer': 'career',
  'career:surgeon': 'career',
  'house:cozy-bungalow': 'home',
  'house:lakeside-villa': 'home',
  'house:lavish-estate': 'home',
  'house:modern-duplex': 'home',
  'house:suburban-townhouse': 'home',
  'house:tiny-cabin': 'home',
  'space:apartment-hunt': 'home',
  'space:bidding-war': 'expense',
  'space:big-promotion': 'career',
  'space:bonus-season': 'gain',
  'space:budget-win': 'gain',
  'space:campus-job': 'gain',
  'space:cap-and-gown': 'grad',
  'space:car-trouble': 'hazard',
  'space:cashback-bonus': 'gain',
  'space:client-win': 'gain',
  'space:conference-talk': 'career',
  'space:corner-office': 'career',
  'space:coupon-clipping': 'gain',
  'space:family-portrait': 'life',
  'space:family-vacation': 'travel',
  'space:finals-week': 'study',
  'space:first-job-fair': 'career',
  'space:first-paycheck': 'gain',
  'space:garage-sale': 'luck',
  'space:garden-harvest': 'gain',
  'space:good-review': 'gain',
  'space:grad-job-fair': 'career',
  'space:grocery-run': 'expense',
  'space:group-project': 'study',
  'space:gym-membership': 'expense',
  'space:house-hunting': 'home',
  'space:interest-payout': 'gain',
  'space:late-night-study': 'study',
  'space:lottery-ticket': 'luck',
  'space:lucky-find': 'life',
  'space:market-crash': 'hazard',
  'space:move-in-day': 'home',
  'space:neighborhood-bbq': 'expense',
  'space:networking-night': 'gain',
  'space:new-baby': 'child',
  'space:new-skills': 'study',
  'space:nursery-setup': 'expense',
  'space:overtime-shift': 'gain',
  'space:pay-raise-talk': 'career',
  'space:payday': 'payday',
  'space:piano-lessons': 'expense',
  'space:poker-night': 'luck',
  'space:quiet-savings': 'gain',
  'space:refund-check': 'gain',
  'space:rent-due': 'expense',
  'space:retirement': 'retire',
  'space:retirement-fund': 'gain',
  'space:ring-shopping': 'love',
  'space:scholarship-win': 'gain',
  'space:school-play': 'life',
  'space:second-baby': 'child',
  'space:side-hustle': 'gain',
  'space:soccer-season': 'life',
  'space:start-of-life': 'life',
  'space:startup-bet': 'luck',
  'space:steady-hustle': 'gain',
  'space:stock-tip': 'invest',
  'space:streaming-bill': 'expense',
  'space:sunset-ahead': 'retire',
  'space:surprise-bonus': 'gain',
  'space:tuition-bill': 'expense',
  'space:wedding-day': 'love',
  'space:weekend-trip': 'travel',
  'space:yard-sale': 'gain',
  'tile:animal-shelter': 'life',
  'tile:backpacking': 'life',
  'tile:cooking-contest': 'life',
  'tile:fantasy-league': 'life',
  'tile:food-blog': 'life',
  'tile:indie-album': 'life',
  'tile:invention': 'life',
  'tile:jingle': 'life',
  'tile:lemonade-stand': 'life',
  'tile:marathon': 'life',
  'tile:mountain-climb': 'life',
  'tile:mural': 'life',
  'tile:novel': 'life',
  'tile:podcast': 'life',
  'tile:pottery': 'life',
  'tile:prize-pumpkin': 'life',
  'tile:rescue-dog': 'life',
  'tile:rescue-kitten': 'life',
  'tile:surfing': 'life',
  'tile:treehouse': 'life',
  'tile:triathlon': 'life',
  'tile:vegetable-garden': 'life',
  'tile:vintage-motorcycle': 'life',
  'tile:youth-coach': 'life',
  'finance:bank-visit': 'invest',
  'finance:insurance-office': 'insurance',
  'finance:policy-auto': 'insurance',
  'finance:policy-home': 'insurance',
  'finance:policy-life': 'insurance',
  'finance:trading-floor': 'invest',
  'stock:green-energy': 'invest',
  'stock:noodle-chain': 'invest',
  'stock:orbital-freight': 'invest',
  'stock:robot-farms': 'invest',
  'stock:studio-pictures': 'invest',
  'space:career-fair-return': 'career',
  'space:child-benefit': 'gain',
  'space:dividend-day': 'invest',
  'space:fender-bender': 'hazard',
  'space:headhunted': 'career',
  'space:home-upgrade': 'home',
  'space:house-fire': 'hazard',
  'space:layoff-notice': 'hazard',
  'space:rival-swap': 'luck',
  'space:school-fees': 'expense',
  'space:sticky-fingers': 'luck',
}
