import { type ComponentType } from 'react'

import type { IconName } from '@domain/model/icons'

import * as careers from './art/careers'
import * as finance from './art/finance'
import { glyphArt } from './art/glyphs'
import * as houses from './art/houses'
import * as spaces from './art/spaces'
import * as stocks from './art/stocks'

/** Life tiles never render above list-chip size, so their art is the star glyph. */
const lifeTile = glyphArt.life

/**
 * Maps every subject the domain can name onto its full-size drawing. The type
 * annotation is what makes a missing illustration a compile error rather than
 * a blank tile discovered in play.
 *
 * This registry only serves large renderings (the event card, the choice
 * modals); anything smaller draws the subject's category glyph instead — see
 * `GameIcon` and `categories.ts`.
 */
export const iconRegistry: Record<IconName, ComponentType> = {
  'career:architect': careers.architect,
  'career:construction-foreman': careers.constructionForeman,
  'career:corporate-lawyer': careers.corporateLawyer,
  'career:delivery-courier': careers.deliveryCourier,
  'career:food-truck-owner': careers.foodTruckOwner,
  'career:game-designer': careers.gameDesigner,
  'career:marine-biologist': careers.marineBiologist,
  'career:pastry-chef': careers.pastryChef,
  'career:pet-groomer': careers.petGroomer,
  'career:salon-owner': careers.salonOwner,
  'career:software-engineer': careers.softwareEngineer,
  'career:surgeon': careers.surgeon,
  'house:cozy-bungalow': houses.cozyBungalow,
  'house:lakeside-villa': houses.lakesideVilla,
  'house:lavish-estate': houses.lavishEstate,
  'house:modern-duplex': houses.modernDuplex,
  'house:suburban-townhouse': houses.suburbanTownhouse,
  'house:tiny-cabin': houses.tinyCabin,
  'space:apartment-hunt': spaces.apartmentHunt,
  'space:bidding-war': spaces.biddingWar,
  'space:big-promotion': spaces.bigPromotion,
  'space:bonus-season': spaces.bonusSeason,
  'space:budget-win': spaces.budgetWin,
  'space:campus-job': spaces.campusJob,
  'space:cap-and-gown': spaces.capAndGown,
  'space:car-trouble': spaces.carTrouble,
  'space:cashback-bonus': spaces.cashbackBonus,
  'space:client-win': spaces.clientWin,
  'space:conference-talk': spaces.conferenceTalk,
  'space:corner-office': spaces.cornerOffice,
  'space:coupon-clipping': spaces.couponClipping,
  'space:family-portrait': spaces.familyPortrait,
  'space:family-vacation': spaces.familyVacation,
  'space:finals-week': spaces.finalsWeek,
  'space:first-job-fair': spaces.firstJobFair,
  'space:first-paycheck': spaces.firstPaycheck,
  'space:garage-sale': spaces.garageSale,
  'space:garden-harvest': spaces.gardenHarvest,
  'space:good-review': spaces.goodReview,
  'space:grad-job-fair': spaces.gradJobFair,
  'space:grocery-run': spaces.groceryRun,
  'space:group-project': spaces.groupProject,
  'space:gym-membership': spaces.gymMembership,
  'space:house-hunting': spaces.houseHunting,
  'space:interest-payout': spaces.interestPayout,
  'space:late-night-study': spaces.lateNightStudy,
  'space:lottery-ticket': spaces.lotteryTicket,
  'space:lucky-find': spaces.luckyFind,
  'space:market-crash': spaces.marketCrash,
  'space:move-in-day': spaces.moveInDay,
  'space:neighborhood-bbq': spaces.neighborhoodBbq,
  'space:networking-night': spaces.networkingNight,
  'space:new-baby': spaces.newBaby,
  'space:new-skills': spaces.newSkills,
  'space:nursery-setup': spaces.nurserySetup,
  'space:overtime-shift': spaces.overtimeShift,
  'space:pay-raise-talk': spaces.payRaiseTalk,
  'space:payday': spaces.payday,
  'space:piano-lessons': spaces.pianoLessons,
  'space:poker-night': spaces.pokerNight,
  'space:quiet-savings': spaces.quietSavings,
  'space:refund-check': spaces.refundCheck,
  'space:rent-due': spaces.rentDue,
  'space:retirement': spaces.retirement,
  'space:retirement-fund': spaces.retirementFund,
  'space:ring-shopping': spaces.ringShopping,
  'space:scholarship-win': spaces.scholarshipWin,
  'space:school-play': spaces.schoolPlay,
  'space:second-baby': spaces.secondBaby,
  'space:side-hustle': spaces.sideHustle,
  'space:soccer-season': spaces.soccerSeason,
  'space:start-of-life': spaces.startOfLife,
  'space:startup-bet': spaces.startupBet,
  'space:steady-hustle': spaces.steadyHustle,
  'space:stock-tip': spaces.stockTip,
  'space:streaming-bill': spaces.streamingBill,
  'space:sunset-ahead': spaces.sunsetAhead,
  'space:surprise-bonus': spaces.surpriseBonus,
  'space:tuition-bill': spaces.tuitionBill,
  'space:wedding-day': spaces.weddingDay,
  'space:weekend-trip': spaces.weekendTrip,
  'space:yard-sale': spaces.yardSale,
  'tile:animal-shelter': lifeTile,
  'tile:backpacking': lifeTile,
  'tile:cooking-contest': lifeTile,
  'tile:fantasy-league': lifeTile,
  'tile:food-blog': lifeTile,
  'tile:indie-album': lifeTile,
  'tile:invention': lifeTile,
  'tile:jingle': lifeTile,
  'tile:lemonade-stand': lifeTile,
  'tile:marathon': lifeTile,
  'tile:mountain-climb': lifeTile,
  'tile:mural': lifeTile,
  'tile:novel': lifeTile,
  'tile:podcast': lifeTile,
  'tile:pottery': lifeTile,
  'tile:prize-pumpkin': lifeTile,
  'tile:rescue-dog': lifeTile,
  'tile:rescue-kitten': lifeTile,
  'tile:surfing': lifeTile,
  'tile:treehouse': lifeTile,
  'tile:triathlon': lifeTile,
  'tile:vegetable-garden': lifeTile,
  'tile:vintage-motorcycle': lifeTile,
  'tile:youth-coach': lifeTile,
  'finance:bank-visit': finance.bankVisit,
  'finance:insurance-office': finance.insuranceOffice,
  'finance:policy-auto': finance.policyAuto,
  'finance:policy-home': finance.policyHome,
  'finance:policy-life': finance.policyLife,
  'finance:trading-floor': finance.tradingFloor,
  'stock:green-energy': stocks.greenEnergy,
  'stock:noodle-chain': stocks.noodleChain,
  'stock:orbital-freight': stocks.orbitalFreight,
  'stock:robot-farms': stocks.robotFarms,
  'stock:studio-pictures': stocks.studioPictures,
  'space:career-fair-return': spaces.careerFairReturn,
  'space:child-benefit': spaces.childBenefit,
  'space:dividend-day': spaces.dividendDay,
  'space:fender-bender': spaces.fenderBender,
  'space:headhunted': spaces.headhunted,
  'space:home-upgrade': spaces.homeUpgrade,
  'space:house-fire': spaces.houseFire,
  'space:layoff-notice': spaces.layoffNotice,
  'space:rival-swap': spaces.rivalSwap,
  'space:school-fees': spaces.schoolFees,
  'space:sticky-fingers': spaces.stickyFingers,
}
